"""add nullable attribute

Revision ID: 37d3ba1f7ec7
Revises: a701742ae8e9
Create Date: 2023-10-20 15:43:27.450331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '37d3ba1f7ec7'
down_revision: Union[str, None] = 'a701742ae8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('posts', 'body',
               existing_type=mysql.VARCHAR(length=15000),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('posts', 'body',
               existing_type=mysql.VARCHAR(length=15000),
               nullable=True)
    op.alter_column('posts', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('posts', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
