"""add user token

Revision ID: e8097a385492
Revises: cd7844192e90
Create Date: 2023-10-24 02:36:00.614450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e8097a385492'
down_revision: Union[str, None] = 'cd7844192e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.create_unique_constraint(None, 'users', ['user_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_token')
    # ### end Alembic commands ###
